#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

#starting nginx service
sudo service nginx start

#allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

#Give user ownership to files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www

#Back up a default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.backp

#Creating a new index
echo -e "Hello World" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx without using systemctl
sudo service nginx restart

echo -e "\nCompleted. \n"
