#!/usr/bin/env bash

# A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Upadating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_for_replacement="location \/redirect_me {\n\treturn 301 https:\/\/github.com\/Fromb23;\n}"
sudo sed -i "s@location \/ {@$string_for_replacement\n\n\tlocation \/ {@g" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart
