#!/usr/bin/env bash
#Tell the story of a passwd
while IFS=: read -r username password userid groupid user_info home_dir shell; do
	# Display user information in the specified format
	echo "The user ${line[0]} is part of the ${line[3]} gang, lives in ${line[5]} and rides ${line[6]}. ${line[2]} place is protected by the passcode ${line[1]}, more info about the user here: ${line[4]}"
done < /etc/passwd
