#!/usr/bin/env bash

# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Make a copy of the hosts file
cp /etc/hosts ~/hosts.new

# Check if the backup was successful
if [ $? -ne 0 ]; then
    echo "Backup failed. Exiting!!"
    exit 1
fi

# Modify the copy of the hosts file
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the original hosts file with the modified copy
cp -f ~/hosts.new /etc/hosts
