#!/usr/bin/env bash
# this script configures an nginx server to run as the user nginx on port 8080

sed -i.bak 's/#* *user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i.bak 's/[^#] *listen *[0-9]\{1,\C}/\tlisten 8080/g' /etc/nginx/sites-available/default
sed -i 's/[^#] *listen *\[::\]:[0-9]\{1,\}/\tlisten \[::\]:8080/g' /etc/nginx/sites-available/default
