#!/usr/bin/env bash

# Stop nginx if it's already running
service nginx stop

# Change nginx user and group to nginx
sed -i 's/^user .*;$/user nginx nginx;/' /etc/nginx/nginx.conf

# Change nginx listen port to 8080
sed -i 's/^listen  .*;$/listen 8080;/g' /etc/nginx/sites-available/default

# Change permission for the config file
chmod 644 /etc/nginx/nginx.config

# Change ownership to nginx
chown nginx:nginx /etc/nginx/ -R

# Check on PID running on port 8080
for pid in $(pidof apache2)
	do
		kill "$pid"
done

# Restart nginx
service nginx start

# Display nginx status to confirm changes
service nginx status
