#!/usr/bin/env bash

# Define the key file name and passphrase
key_name="school"
key_bits="4096"
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -f $key_name -N $passphrase
